### ISSUE TITLE
[Script Error]

### ISSUE THREAD

**Issue by Heatwu** [Cryotheus/e2_game_core#1]
**Steps To Reproduce**
on gmod x64
start a LAN game

**Script Errors**
```
[[E2] Game Core] lua/wire_game_core/client.lua:1170: attempt to index upvalue 'rich_text_track' (a nil value)
  1. unknown - lua/wire_game_core/client.lua:1170
```

**Comment by Cryotheus** [comment]
I appreciate the report, however:
(**TL;DR**) This project has been abandoned, thus no action will be taken.

I am not working on, or maintaining this project. Since I first started this project, I have gotten much better at GLua. This project needs a rewrite, and additionally will need its own administration mod to grant me the level of control necessary to achieve the image I had when starting this project. I will be archiving this repo as there will be no more commits.
